//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace EmcHack1
{
    using System.Xml.Serialization;

    // 
    // This source code was auto-generated by xsd, Version=4.0.30319.33440.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class coverage
    {

        private string rebasedpathsField;

        private string filtersField;

        //private coverageDocumentsDoc[][] documentsField;

        private coverageModule[] moduleField;

        private string profilerVersionField;

        private string driverVersionField;

        private string exportversionField;

        private string viewdisplaynameField;

        private string startTimeField;

        private string measureTimeField;

        private string projectNameField;

        private string buildidField;

        private string coveragenodeidField;

        private string failedField;

        private string satisfactorybranchthresholdField;

        private string satisfactorycoveragethresholdField;

        private string satisfactorycyclomaticcomplexitythresholdField;

        private string satisfactoryfunctionthresholdField;

        private string satisfactoryunvisitedsequencepointsField;

        private string uiviewtypeField;

        private string viewguidField;

        private string viewfilterstyleField;

        private string viewreportstyleField;

        private string viewsortstyleField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string rebasedpaths
        {
            get
            {
                return this.rebasedpathsField;
            }
            set
            {
                this.rebasedpathsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string filters
        {
            get
            {
                return this.filtersField;
            }
            set
            {
                this.filtersField = value;
            }
        }

        ///// <remarks/>
        //[System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        //[System.Xml.Serialization.XmlArrayItemAttribute("doc", typeof(coverageDocumentsDoc), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        //public coverageDocumentsDoc[][] documents
        //{
        //    get
        //    {
        //        return this.documentsField;
        //    }
        //    set
        //    {
        //        this.documentsField = value;
        //    }
        //}

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("module", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public coverageModule[] module
        {
            get
            {
                return this.moduleField;
            }
            set
            {
                this.moduleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string profilerVersion
        {
            get
            {
                return this.profilerVersionField;
            }
            set
            {
                this.profilerVersionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string driverVersion
        {
            get
            {
                return this.driverVersionField;
            }
            set
            {
                this.driverVersionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string exportversion
        {
            get
            {
                return this.exportversionField;
            }
            set
            {
                this.exportversionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string viewdisplayname
        {
            get
            {
                return this.viewdisplaynameField;
            }
            set
            {
                this.viewdisplaynameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string startTime
        {
            get
            {
                return this.startTimeField;
            }
            set
            {
                this.startTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string measureTime
        {
            get
            {
                return this.measureTimeField;
            }
            set
            {
                this.measureTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string projectName
        {
            get
            {
                return this.projectNameField;
            }
            set
            {
                this.projectNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string buildid
        {
            get
            {
                return this.buildidField;
            }
            set
            {
                this.buildidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string coveragenodeid
        {
            get
            {
                return this.coveragenodeidField;
            }
            set
            {
                this.coveragenodeidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string failed
        {
            get
            {
                return this.failedField;
            }
            set
            {
                this.failedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string satisfactorybranchthreshold
        {
            get
            {
                return this.satisfactorybranchthresholdField;
            }
            set
            {
                this.satisfactorybranchthresholdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string satisfactorycoveragethreshold
        {
            get
            {
                return this.satisfactorycoveragethresholdField;
            }
            set
            {
                this.satisfactorycoveragethresholdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string satisfactorycyclomaticcomplexitythreshold
        {
            get
            {
                return this.satisfactorycyclomaticcomplexitythresholdField;
            }
            set
            {
                this.satisfactorycyclomaticcomplexitythresholdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string satisfactoryfunctionthreshold
        {
            get
            {
                return this.satisfactoryfunctionthresholdField;
            }
            set
            {
                this.satisfactoryfunctionthresholdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string satisfactoryunvisitedsequencepoints
        {
            get
            {
                return this.satisfactoryunvisitedsequencepointsField;
            }
            set
            {
                this.satisfactoryunvisitedsequencepointsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string uiviewtype
        {
            get
            {
                return this.uiviewtypeField;
            }
            set
            {
                this.uiviewtypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string viewguid
        {
            get
            {
                return this.viewguidField;
            }
            set
            {
                this.viewguidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string viewfilterstyle
        {
            get
            {
                return this.viewfilterstyleField;
            }
            set
            {
                this.viewfilterstyleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string viewreportstyle
        {
            get
            {
                return this.viewreportstyleField;
            }
            set
            {
                this.viewreportstyleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string viewsortstyle
        {
            get
            {
                return this.viewsortstyleField;
            }
            set
            {
                this.viewsortstyleField = value;
            }
        }
    }

    /// <remarks/>
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    //[System.SerializableAttribute()]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    //[System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    //public partial class coverageDocumentsDoc
    //{

    //    private string idField;

    //    private string excludedField;

    //    private string urlField;

    //    private string csField;

    //    private string csaField;

    //    private string omField;

    //    private string nidField;

    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlAttributeAttribute()]
    //    public string id
    //    {
    //        get
    //        {
    //            return this.idField;
    //        }
    //        set
    //        {
    //            this.idField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlAttributeAttribute()]
    //    public string excluded
    //    {
    //        get
    //        {
    //            return this.excludedField;
    //        }
    //        set
    //        {
    //            this.excludedField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlAttributeAttribute()]
    //    public string url
    //    {
    //        get
    //        {
    //            return this.urlField;
    //        }
    //        set
    //        {
    //            this.urlField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlAttributeAttribute()]
    //    public string cs
    //    {
    //        get
    //        {
    //            return this.csField;
    //        }
    //        set
    //        {
    //            this.csField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlAttributeAttribute()]
    //    public string csa
    //    {
    //        get
    //        {
    //            return this.csaField;
    //        }
    //        set
    //        {
    //            this.csaField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlAttributeAttribute()]
    //    public string om
    //    {
    //        get
    //        {
    //            return this.omField;
    //        }
    //        set
    //        {
    //            this.omField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlAttributeAttribute()]
    //    public string nid
    //    {
    //        get
    //        {
    //            return this.nidField;
    //        }
    //        set
    //        {
    //            this.nidField = value;
    //        }
    //    }
    //}

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class coverageModule
    {

        private coverageModuleClass[] classField;

        private string moduleIdField;

        private string nameField;

        private string assemblyField;

        private string assemblyIdentityField;

        private string nidField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("class", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public coverageModuleClass[] @class
        {
            get
            {
                return this.classField;
            }
            set
            {
                this.classField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string moduleId
        {
            get
            {
                return this.moduleIdField;
            }
            set
            {
                this.moduleIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string assembly
        {
            get
            {
                return this.assemblyField;
            }
            set
            {
                this.assemblyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string assemblyIdentity
        {
            get
            {
                return this.assemblyIdentityField;
            }
            set
            {
                this.assemblyIdentityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string nid
        {
            get
            {
                return this.nidField;
            }
            set
            {
                this.nidField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class coverageModuleClass
    {

        private coverageModuleClassMethod[] methodField;

        private string nameField;

        private string signatureField;

        private string excludedField;

        private string nidField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("method", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public coverageModuleClassMethod[] method
        {
            get
            {
                return this.methodField;
            }
            set
            {
                this.methodField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string signature
        {
            get
            {
                return this.signatureField;
            }
            set
            {
                this.signatureField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string excluded
        {
            get
            {
                return this.excludedField;
            }
            set
            {
                this.excludedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string nid
        {
            get
            {
                return this.nidField;
            }
            set
            {
                this.nidField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class coverageModuleClassMethod
    {

        private coverageModuleClassMethodSeqpnt[] seqpntField;

        private string nameField;

        private string signatureField;

        private string excludedField;

        private string instrumentedField;

        private string ccField;

        private string vcField;

        private string nidField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("seqpnt", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public coverageModuleClassMethodSeqpnt[] seqpnt
        {
            get
            {
                return this.seqpntField;
            }
            set
            {
                this.seqpntField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string signature
        {
            get
            {
                return this.signatureField;
            }
            set
            {
                this.signatureField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string excluded
        {
            get
            {
                return this.excludedField;
            }
            set
            {
                this.excludedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string instrumented
        {
            get
            {
                return this.instrumentedField;
            }
            set
            {
                this.instrumentedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string cc
        {
            get
            {
                return this.ccField;
            }
            set
            {
                this.ccField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string vc
        {
            get
            {
                return this.vcField;
            }
            set
            {
                this.vcField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string nid
        {
            get
            {
                return this.nidField;
            }
            set
            {
                this.nidField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class coverageModuleClassMethodSeqpnt
    {

        private string vcField;

        private string oField;

        private string lField;

        private string elField;

        private string cField;

        private string ecField;

        private string exField;

        private string flField;

        private string docField;

        private string nidField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string vc
        {
            get
            {
                return this.vcField;
            }
            set
            {
                this.vcField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string o
        {
            get
            {
                return this.oField;
            }
            set
            {
                this.oField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string l
        {
            get
            {
                return this.lField;
            }
            set
            {
                this.lField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string el
        {
            get
            {
                return this.elField;
            }
            set
            {
                this.elField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string c
        {
            get
            {
                return this.cField;
            }
            set
            {
                this.cField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ec
        {
            get
            {
                return this.ecField;
            }
            set
            {
                this.ecField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ex
        {
            get
            {
                return this.exField;
            }
            set
            {
                this.exField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string fl
        {
            get
            {
                return this.flField;
            }
            set
            {
                this.flField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string doc
        {
            get
            {
                return this.docField;
            }
            set
            {
                this.docField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string nid
        {
            get
            {
                return this.nidField;
            }
            set
            {
                this.nidField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class NewDataSet
    {

        private coverage[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("coverage")]
        public coverage[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

}